version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Docker...
      - yum update -y
      - yum install -y docker
      - service docker start
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 942948037842.dkr.ecr.ap-south-1.amazonaws.com
      - echo Creating ECR repositories if not exists...
      - aws ecr describe-repositories --repository-names journalism-service || aws ecr create-repository --repository-name journalism-service
      - aws ecr describe-repositories --repository-names mysql || aws ecr create-repository --repository-name mysql
  build:
    commands:
      - echo Building Spring Boot Docker image...
      - docker build -t journalism-service .
      - docker tag journalism-service:latest 942948037842.dkr.ecr.ap-south-1.amazonaws.com/journalism-service:latest
      - echo Pulling and tagging MySQL image...
      - docker pull mysql:8.0
      - docker tag mysql:8.0 942948037842.dkr.ecr.ap-south-1.am
